plugins:
  discourse_hide_categories_enabled:
    default: false
    client: true
  permanently_hidden_categories:
    type: list
    default: ""
    client: true
  discourse_hide_categories_replace_restricted_icon:
    default: 'lock'
    client: true
